Update trigger playbook for creating bm trigger
We have created a baremetal job that will trigger in
downstream zuul for master c9 integration line.
We need a trigger job for baremetal similiar to sc010
kvm trigger job.

Updating scenario010-kvm-trigger.yaml to parameterize
the commit msg and also add a trigger_job_name var
that defaults to blank string.

For baremetal trigger, we will create a trigger
file: trigger_master_centos_9baremetal

This is second attempt to update this playbook. We had to revert
earlier patch[1] because we missed quotes around "{{ }}" and trigger
jobs failed with below:-

~~~
$ git commit -mTrigger for scenario010-kvm
error: pathspec 'for' did not match any file(s) known to git
error: pathspec 'scenario010-kvm' did not match any file(s) known to git
~~~

wrong:-
git commit -m{{ trigger_commit_msg|default('Trigger for scenario010-kvm') }}

correct:-
git commit -m"{{ trigger_commit_msg|default('Trigger for
scenario010-kvm') }}"

[1] https://review.rdoproject.org/r/c/config/+/42330

Change-Id: Ib70b2caba7d79a9ebd976b16ff89ad23aa5608eb