Install latest openstacksdk version in cs10
CS10 job is hitting post-failure while running
openstack port show compute-0-34bc20ff-837e-4414-acc8-e58022140752 -f yaml command.
ON CS10 env, python-openstackclient-10.3.0, openstacksdk-4.1.0 is installed,
causing openstack cli to fail with
AttributeError: module 'openstack.compute.v2' has no attribute 'Proxy'.
Did you mean: '_proxy'?,
Updating to latest openstacksdk fixes it.
Below is the proof from node
```
[zuul@controller ~]$ openstack port show compute-0-34bc20ff-837e-4414-acc8-e58022140752 -f yaml
Traceback (most recent call last):
  File "/usr/local/bin/openstack", line 5, in <module>
    from openstackclient.shell import main
  File "/usr/local/lib/python3.12/site-packages/openstackclient/shell.py", line 29, in <module>
    from openstackclient.common import clientmanager
  File "/usr/local/lib/python3.12/site-packages/openstackclient/common/clientmanager.py", line 43, in <module>
    class ClientManager(clientmanager.ClientManager):
  File "/usr/local/lib/python3.12/site-packages/openstackclient/common/clientmanager.py", line 58, in ClientManager
    compute: compute_v2.Proxy
             ^^^^^^^^^^^^^^^^
AttributeError: module 'openstack.compute.v2' has no attribute 'Proxy'. Did you mean: '_proxy'?
[zuul@controller ~]$ cat /etc/redhat-release
CentOS Stream release 10 (Coughlan)
[zuul@controller ~]$ rpm -qa | grep python-openstackclient
[zuul@controller ~]$ openstack --version
Traceback (most recent call last):
  File "/usr/local/bin/openstack", line 5, in <module>
    from openstackclient.shell import main
  File "/usr/local/lib/python3.12/site-packages/openstackclient/shell.py", line 29, in <module>
    from openstackclient.common import clientmanager
  File "/usr/local/lib/python3.12/site-packages/openstackclient/common/clientmanager.py", line 43, in <module>
    class ClientManager(clientmanager.ClientManager):
  File "/usr/local/lib/python3.12/site-packages/openstackclient/common/clientmanager.py", line 58, in ClientManager
    compute: compute_v2.Proxy
             ^^^^^^^^^^^^^^^^
AttributeError: module 'openstack.compute.v2' has no attribute 'Proxy'. Did you mean: '_proxy'?
[zuul@controller ~]$ pip list | grep openstack
openstacksdk              4.1.0
python-openstackclient    10.3.0
[zuul@controller ~]$ pip install -u openstacksdk

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -u
[zuul@controller ~]$ pip install -U openstacksdk
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openstacksdk in ./.local/lib/python3.12/site-packages (4.1.0)
Collecting openstacksdk
  Downloading openstacksdk-4.20.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: cryptography>=2.7 in ./.local/lib/python3.12/site-packages (from openstacksdk) (43.0.3)
Requirement already satisfied: decorator>=4.4.1 in /usr/local/lib/python3.12/site-packages (from openstacksdk) (5.3.1)
Requirement already satisfied: dogpile.cache>=0.6.5 in /usr/local/lib/python3.12/site-packages (from openstacksdk) (1.5.0)
Requirement already satisfied: iso8601>=0.1.11 in /usr/local/lib/python3.12/site-packages (from openstacksdk) (2.1.0)
Requirement already satisfied: jmespath>=0.9.0 in /usr/local/lib/python3.12/site-packages (from openstacksdk) (1.1.0)
Requirement already satisfied: jsonpatch!=1.20,>=1.16 in /usr/lib/python3.12/site-packages (from openstacksdk) (1.33)
Requirement already satisfied: keystoneauth1>=5.16.0 in /usr/local/lib/python3.12/site-packages (from openstacksdk) (5.17.0)
Requirement already satisfied: os-service-types>=1.8.1 in /usr/local/lib/python3.12/site-packages (from openstacksdk) (1.9.0)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /usr/local/lib/python3.12/site-packages (from openstacksdk) (7.0.3)
Requirement already satisfied: platformdirs>=3 in /usr/local/lib/python3.12/site-packages (from openstacksdk) (4.11.8)
Requirement already satisfied: psutil>=3.2.2 in /usr/local/lib64/python3.12/site-packages (from openstacksdk) (7.2.2)
Requirement already satisfied: PyYAML>=3.13 in /usr/lib64/python3.12/site-packages (from openstacksdk) (6.0.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib64/python3.12/site-packages (from cryptography>=2.7->openstacksdk) (2.1.1)
Requirement already satisfied: stevedore>=3.0.0 in /usr/local/lib/python3.12/site-packages (from dogpile.cache>=0.6.5->openstacksdk) (5.9.1)
Requirement already satisfied: jsonpointer>=1.9 in /usr/lib/python3.12/site-packages (from jsonpatch!=1.20,>=1.16->openstacksdk) (2.3)
Requirement already satisfied: requests>=2.14.2 in /usr/lib/python3.12/site-packages (from keystoneauth1>=5.16.0->openstacksdk) (2.32.4)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/site-packages (from keystoneauth1>=5.16.0->openstacksdk) (4.16.0)
Requirement already satisfied: setuptools in /usr/lib/python3.12/site-packages (from pbr!=2.1.0,>=2.0.0->openstacksdk) (69.0.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/site-packages (from cffi>=1.12->cryptography>=2.7->openstacksdk) (3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.12/site-packages (from requests>=2.14.2->keystoneauth1>=5.16.0->openstacksdk) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.12/site-packages (from requests>=2.14.2->keystoneauth1>=5.16.0->openstacksdk) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3.12/site-packages (from requests>=2.14.2->keystoneauth1>=5.16.0->openstacksdk) (1.26.19)
Downloading openstacksdk-4.20.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 42.5 MB/s eta 0:00:00
Installing collected packages: openstacksdk
  Attempting uninstall: openstacksdk
    Found existing installation: openstacksdk 4.1.0
    Uninstalling openstacksdk-4.1.0:
      Successfully uninstalled openstacksdk-4.1.0
Successfully installed openstacksdk-4.20.0
[zuul@controller ~]$ openstack --version
openstack 10.3.0
[zuul@controller ~]$ openstack port show compute-0-34bc20ff-837e-4414-acc8-e58022140752 -f yaml
Missing value auth-url required for auth plugin password
```

Links:
[1]. https://gateway-cloud-softwarefactory.apps.ocp.cloud.ci.centos.org/zuul/t/rdoproject.org/build/777bb7e6b4e1485081c532acd746818c

Change-Id: I079cd1d02db21be65675b7207aef193f24edde28
Signed-off-by: Chandan <chkumar@redhat.com>