config-check: use yaml.safe_load
It seems like the new yaml version no longer support `yaml.load(file)`,
and it is throwing a TypeError: missing 1 required positional argument: 'Loader'

Change-Id: Ie11e37b7d0869b283993a2a407981112b663d3e4